name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 1 * *" # Run at midnight on the first day of every month
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: true
